# Arch Server v5.1 - YAML Lint Configuration

extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore: |
  .venv/
  node_modules/
  .gitlab-ci.yml
